services:
  db:
    image: postgres:16
    container_name: postgres_db_donare
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5435:5432"
    restart: unless-stopped

  web:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app 
      - ./backend/media:/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build: ./frontend 
    container_name: frontend_donare
    volumes:
      - ./frontend:/app 
      - /app/node_modules
    ports:
      - "5174:5173"
    stdin_open: true
    tty: true
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
